### ISSUE TITLE
Not able to run the example

### ISSUE THREAD

**Issue by Jayendran-p** [elvisfernandes/dfservice-example#1]
Hi Elvis,

I am not able to run the example as it fails in npm install ng2-dfservice

**Comment by elvisfernandes** [comment]
Hi @Jayendran-p,

As replied on the issue #1 you opened on ng2-dfservice repo, try installing typings and run the example again.

Let me know if it works.

**Comment by elvisfernandes** [comment]
Closing this ticket as this issue will be managed at ticket [#1 of ng2-dfservice](https://github.com/elvisfernandes/ng2-dfservice/issues/1)
